exception_logger/__init__.py,sha256=Wg_Z8eeF_ZxMhOfyfyl6ELcpG1of3tHqDDTe7E51rRU,37
exception_logger/json_logger.py,sha256=TSlxfjlWnafQh9f1uafpQ_24XjbulFTJk6K_cYs2O-w,1216
json_exception_logger-2.0.0.dist-info/METADATA,sha256=Dki4dv6Lun1_xHZ_JIvGEJdCuXPEDsedoWCHC1Ael-o,150
json_exception_logger-2.0.0.dist-info/WHEEL,sha256=R0nc6qTxuoLk7ShA2_Y-UWkN8ZdfDBG2B6Eqpz2WXbs,91
json_exception_logger-2.0.0.dist-info/top_level.txt,sha256=3OZXBFxvVMBjQpvg6T2Hxt4oviBkizfV6XBADM9wX14,17
json_exception_logger-2.0.0.dist-info/RECORD,,
